import Head from "next/head";
import Container from "./Container";
import Header from "./Header";
import MainContainer from "./MainContainer";

type LayoutProps = {
  isHome?: boolean;
  children: React.ReactNode;
};

const Layout = (props: LayoutProps) => {
  return (
    <>
      <Head>
        <title>Discuss</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainContainer>
        <Header />
        <Container>{props.children}</Container>
      </MainContainer>
    </>
  );
};

export default Layout;
